version = 0.1

[default.deploy.parameters]
stack_name = "ssu-announcement"
resolve_s3 = true
s3_prefix = "ssu-announcement"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AnnouncementTableName=\"ssu-announcements\" SubscriptionTableName=\"ssu-subscriptions\" QueueName=\"ssu-notification-queue\" DomainName=\"ssunnounce.sssupport.shop\""
image_repositories = []
confirm_changeset = true

[default.global.parameters]
region = "ap-northeast-2"
